### ISSUE TITLE
NullPointerException if no attribute alias is specified

### ISSUE THREAD

**Issue by sbarlabanov** [DataDog/jmxfetch#123]
The following attribute configuration results in a NullPointerException in 0.12.0:

```
            - include:
               bean: org.datadog.jmxfetch.test:type=SimpleTestJavaApp,scope=Co|olScope,host=localhost,component=
               attribute:
                    ShouldBe100:
                        metric_type: gauge
```
I reproduced it in a unit test:
Exception is:
```
java.lang.NullPointerException
	at org.datadog.jmxfetch.JMXAttribute.getUserAlias(JMXAttribute.java:445)
	at org.datadog.jmxfetch.JMXAttribute.getAlias(JMXAttribute.java:385)
	at org.datadog.jmxfetch.JMXAttribute.getAlias(JMXAttribute.java:462)
	at org.datadog.jmxfetch.JMXSimpleAttribute.getMetrics(JMXSimpleAttribute.java:31)
	at org.datadog.jmxfetch.Instance.getMetrics(Instance.java:164)
	at org.datadog.jmxfetch.App.doIteration(App.java:182)
	at org.datadog.jmxfetch.TestCommon.run(TestCommon.java:99)
	at org.datadog.jmxfetch.TestApp.testBeanTags(TestApp.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by yannmh** [comment]
Thanks for reporting @sbarlabanov,

This is indeed an issue: `alias`, `metric_type`.. are optional parameters. However it seems that the code is expecting all parameters if one is defined. 

An alternative syntax/workaround, when `metric_type` set to gauge, is to have:

```
            - include:
               bean: org.datadog.jmxfetch.test:type=SimpleTestJavaApp,scope=Co|olScope,host=localhost,component=
               attribute:
                    - ShouldBe100
```

**Comment by khelenek** [comment]
This is still happening to me on Mac, Collector (v 5.11.3)
Platform: Darwin-15.6.0-x86_64-i386-64bit
  Python Version: 2.7.12, 64bit
