### ISSUE TITLE
Classcast exception "java.lang.Integer cannot be cast to java.lang.String"

### ISSUE THREAD

**Issue by probert-mtv** [DataDog/jmxfetch#196]
If the password is only a number, like 123, an exception is raised:

2018-11-05 13:05:43 EST | INFO | (jmxfetch.go:209 in func1) | 2018-11-05 13:05:43,912 | ERROR| App | Unexpected exception while initiating instance localhost:2028 : java.lang.Integer cannot be cast to java.lang.String
2018-11-05 13:05:43 EST | INFO | (jmxfetch.go:209 in func1) | java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
2018-11-05 13:05:43 EST | INFO | (jmxfetch.go:209 in func1) | 	at org.datadog.jmxfetch.RemoteConnection.<init>(RemoteConnection.java:52)
2018-11-05 13:05:43 EST | INFO | (jmxfetch.go:209 in func1) | 	at org.datadog.jmxfetch.ConnectionFactory.createConnection(ConnectionFactory.java:29)
2018-11-05 13:05:43 EST | INFO | (jmxfetch.go:209 in func1) | 	at org.datadog.jmxfetch.Instance.getConnection(Instance.java:221)
2018-11-05 13:05:43 EST | INFO | (jmxfetch.go:209 in func1) | 	at org.datadog.jmxfetch.Instance.init(Instance.java:232)
2018-11-05 13:05:43 EST | INFO | (jmxfetch.go:209 in func1) | 	at org.datadog.jmxfetch.App.instantiate(App.java:642)
2018-11-05 13:05:43 EST | INFO | (jmxfetch.go:209 in func1) | 	at org.datadog.jmxfetch.App.init(App.java:707)
2018-11-05 13:05:43 EST | INFO | (jmxfetch.go:209 in func1) | 	at org.datadog.jmxfetch.App.run(App.java:149)
2018-11-05 13:05:43 EST | INFO | (jmxfetch.go:209 in func1) | 	at org.datadog.jmxfetch.App.main(App.java:100)

**Comment by olivielpeau** [comment]
Hi @probert-mtv, thanks for opening this PR. This likely happens because you define you password in your yaml config as a yaml integer. Defining it as a string instead should work, e.g. use:

```yaml
password: "123"
```

instead of 

```yaml
password: 123
```

Let me know if this fixes the issue for you
