### ISSUE TITLE
NullPointerException when logging unsupported attribute type

### ISSUE THREAD

**Issue by clofresh** [DataDog/jmxfetch#29]
java.lang.NullPointerException
at
javax.management.MBeanAttributeInfo.hashCode(MBeanAttributeInfo.java:217)
at java.lang.Object.toString(Object.java:209)
at java.lang.String.valueOf(String.java:2615)
at java.lang.StringBuilder.append(StringBuilder.java:116)
at org.datadog.jmxfetch.Instance._getMatchingAttributes(Instance.java:195)
at org.datadog.jmxfetch.Instance.init(Instance.java:90)
at org.datadog.jmxfetch.App.init(App.java:295)
at org.datadog.jmxfetch.App.main(App.java:82)

Running v 0.2.0 but issue still exists on master

**Comment by carlosroman** [comment]
Closing as this is now fixed [here](https://github.com/DataDog/jmxfetch/blob/master/src/main/java/org/datadog/jmxfetch/Instance.java#L754).
