### ISSUE TITLE
Flakey test in some JVM versions

### ISSUE THREAD

**Issue by scottopell** [DataDog/jmxfetch#440]
In `TestInstance`, the `testEmptyDefaultHostname` test is flakey under some recent JVM versions.

Reproducible by simply running it locally multiple times, sometimes it passes and sometimes it fails.
`mvn test -Dtest=TestInstance#testEmptyDefaultHostname`

It appears that there are two `Instance`s configured to run in this test, and in the case where it fails, one of the two `Instance`s fails to initialize with the following error:

```
2023-05-18 16:44:50 UTC | JMX | WARN | App | Could not initialize instance: jmx_test_no_hostname:
java.util.concurrent.ExecutionException: java.lang.InternalError: java.lang.IllegalArgumentException: Could not find MonitoredHost for scheme: local
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.datadog.jmxfetch.App.processRecoveryResults(App.java:953)
	at org.datadog.jmxfetch.App$5.invoke(App.java:927)
	at org.datadog.jmxfetch.tasks.TaskProcessor.processTasks(TaskProcessor.java:63)
	at org.datadog.jmxfetch.App.init(App.java:917)
	at org.datadog.jmxfetch.TestCommon.initApplication(TestCommon.java:163)
	at org.datadog.jmxfetch.TestCommon.initApplication(TestCommon.java:167)
	at org.datadog.jmxfetch.TestInstance.testEmptyDefaultHostname(TestInstance.java:61)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:45)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
Caused by: java.lang.InternalError: java.lang.IllegalArgumentException: Could not find MonitoredHost for scheme: local
	at jdk.attach/sun.tools.attach.HotSpotAttachProvider.listVirtualMachines(HotSpotAttachProvider.java:84)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.list(VirtualMachine.java:146)
	at org.datadog.jmxfetch.AttachApiConnection.getJmxUrlForProcessRegex(AttachApiConnection.java:40)
	at org.datadog.jmxfetch.AttachApiConnection.getAddress(AttachApiConnection.java:30)
	at org.datadog.jmxfetch.AttachApiConnection.<init>(AttachApiConnection.java:22)
	at org.datadog.jmxfetch.ConnectionFactory.createConnection(ConnectionFactory.java:34)
	at org.datadog.jmxfetch.Instance.getConnection(Instance.java:406)
	at org.datadog.jmxfetch.Instance.init(Instance.java:419)
	at org.datadog.jmxfetch.InstanceInitializingTask.call(InstanceInitializingTask.java:15)
	at org.datadog.jmxfetch.InstanceInitializingTask.call(InstanceInitializingTask.java:3)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalArgumentException: Could not find MonitoredHost for scheme: local
	at jdk.internal.jvmstat/sun.jvmstat.monitor.MonitoredHost.getMonitoredHost(MonitoredHost.java:177)
	at jdk.attach/sun.tools.attach.HotSpotAttachProvider.listVirtualMachines(HotSpotAttachProvider.java:72)
	... 13 more
```

It always appears to be the second instance that fails.

**Comment by scottopell** [comment]
Similar error appears in https://github.com/oracle/visualvm/issues/99 which links out to https://bugs.openjdk.org/browse/JDK-8252587

Haven't tested very extensively, but I'm able to reliably reproduce in openjdk-19 and not able to reproduce even once in `liberica-8u265+1`
