### ISSUE TITLE
"Unexpected exception while initiating instance" exception

### ISSUE THREAD

**Issue by dparshin** [DataDog/jmxfetch#61]
Here is output of 'datadog-agent jmx list_collected_attributes' command:

```
#####################################
Instance: localhost:9110
#####################################

       Matching: 1/350. Bean name: java.lang:type=GarbageCollector,name=ParNew - Attribute name: CollectionCount  - Attribute type: long
       Matching: 2/350. Bean name: java.lang:type=GarbageCollector,name=ParNew - Attribute name: CollectionTime  - Attribute type: long
       Matching: 3/350. Bean name: java.lang:type=GarbageCollector,name=ConcurrentMarkSweep - Attribute name: CollectionCount  - Attribute type: long
       Matching: 4/350. Bean name: java.lang:type=GarbageCollector,name=ConcurrentMarkSweep - Attribute name: CollectionTime  - Attribute type: long
       Matching: 5/350. Bean name: java.lang:type=Threading - Attribute name: ThreadCount  - Attribute type: int
       Matching: 6/350. Bean name: java.lang:type=OperatingSystem - Attribute name: OpenFileDescriptorCount  - Attribute type: long
jmx[instance:staticcache] - 1433262458 = ERROR
2015-06-02 12:27:38,113 | ERROR | App | Unexpected exception while initiating instance localhost:9110 : 1
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.datadog.jmxfetch.JMXAttribute.getBeanParametersHash(JMXAttribute.java:70)
	at org.datadog.jmxfetch.JMXAttribute.<init>(JMXAttribute.java:59)
	at org.datadog.jmxfetch.JMXSimpleAttribute.<init>(JMXSimpleAttribute.java:24)
	at org.datadog.jmxfetch.Instance.getMatchingAttributes(Instance.java:221)
	at org.datadog.jmxfetch.Instance.init(Instance.java:120)
	at org.datadog.jmxfetch.App.init(App.java:330)
	at org.datadog.jmxfetch.App.main(App.java:91)
```

Integration doesn't work for us b/c of this. Please let me know if you need more data.

**Comment by remh** [comment]
Hi @dparshin .

There is likely something wrong in your yaml file (more specifically in the tags section). Could you send it over to the support team please ? 
support _at datadoghq.com
